import { action } from '@ladle/react'
import { PayrollOverviewPresentation } from './PayrollOverviewPresentation'

export default {
  title: 'Domain/Payroll/PayrollOverview',
}

export const PayrollOverviewStory = () => {
  return (
    <PayrollOverviewPresentation
      onEdit={action('edit')}
      onSubmit={action('submit')}
      payrollData={{
        payrollDeadline: new Date('2025-09-24T23:00:00.000Z'),
        checkDate: '2025-09-26',
        processed: false,
        processedDate: null,
        calculatedAt: new Date('2025-09-15T16:25:07.000Z'),
        uuid: '9f2013b1-caa6-4b49-8ae2-abc988615808',
        payrollUuid: '9f2013b1-caa6-4b49-8ae2-abc988615808',
        companyUuid: '624e94a3-da0a-48e1-9f9b-667f8d502ce1',
        offCycle: false,
        autoPilot: false,
        external: false,
        payPeriod: {
          startDate: '2025-09-12',
          endDate: '2025-09-18',
          payScheduleUuid: '3bef2adc-5ffb-4575-94d7-2e34c3e7c0ac',
        },
        totals: {
          companyDebit: '15370.81',
          netPayDebit: '10453.44',
          taxDebit: '4917.37',
          reimbursementDebit: '0.00',
          childSupportDebit: '0.00',
          reimbursements: '0.00',
          netPay: '10453.44',
          grossPay: '13754.60',
          employeeBonuses: '0.00',
          employeeCommissions: '0.00',
          employeeCashTips: '0.00',
          employeePaycheckTips: '0.00',
          additionalEarnings: '0.00',
          ownersDraw: '0.00',
          checkAmount: '0.00',
          employerTaxes: '1616.21',
          employeeTaxes: '3301.16',
          benefits: '0.00',
          employeeBenefitsDeductions: '0.00',
          imputedPay: '0.00',
          deferredPayrollTaxes: '0.00',
          otherDeductions: '0.00',
        },
        companyTaxes: [],
        createdAt: new Date('2025-09-15T16:19:04.000Z'),
        submissionBlockers: [],
        processingRequest: {
          status: 'calculate_success',
          errors: [],
        },
        partnerOwnedDisbursement: false,
        employeeCompensations: [
          {
            employeeUuid: '7aef801c-19e3-469c-a8b3-ce3437f9b88f',
            excluded: false,
            version: '0a62b7aaaf503f4f48936b424852035f',
            grossPay: 440,
            netPay: 384,
            checkAmount: 384,
            paymentMethod: 'Direct Deposit',
            memo: null,
            fixedCompensations: [],
            hourlyCompensations: [
              {
                name: 'Regular Hours',
                hours: '20.000',
                amount: '440.0',
                jobUuid: '3834f43e-3905-4690-869b-5e9b4dd4b613',
                compensationMultiplier: 1,
                flsaStatus: 'Nonexempt',
              },
            ],
            paidTimeOff: [
              {
                name: 'Vacation Hours',
                hours: '0.0',
              },
              {
                name: 'Sick Hours',
                hours: '0.0',
              },
              {
                name: 'Holiday Hours',
                hours: '0.0',
              },
            ],
            taxes: [
              {
                name: 'Federal Income Tax',
                employer: false,
                amount: 15.15,
              },
              {
                name: 'Social Security',
                employer: false,
                amount: 27.28,
              },
              {
                name: 'Social Security',
                employer: true,
                amount: 27.28,
              },
              {
                name: 'Medicare',
                employer: false,
                amount: 6.38,
              },
              {
                name: 'Medicare',
                employer: true,
                amount: 6.38,
              },
              {
                name: 'CA State Income Tax',
                employer: false,
                amount: 1.91,
              },
              {
                name: 'FUTA',
                employer: true,
                amount: 2.64,
              },
              {
                name: 'CA SUI',
                employer: true,
                amount: 14.96,
              },
              {
                name: 'CA SDI',
                employer: false,
                amount: 5.28,
              },
              {
                name: 'CA ETT',
                employer: true,
                amount: 0.44,
              },
            ],
            benefits: [],
            deductions: [],
          },
          {
            employeeUuid: 'd73de8ef-a54c-4979-a4d6-f1c64a13963b',
            excluded: false,
            version: '476eac712965314180b03aac258fc9ad',
            grossPay: 1500,
            netPay: 1132.26,
            checkAmount: 1132.26,
            paymentMethod: 'Direct Deposit',
            memo: null,
            fixedCompensations: [],
            hourlyCompensations: [
              {
                name: 'Regular Hours',
                hours: '20.000',
                amount: '1500.0',
                jobUuid: 'd1d6b37c-1335-403f-8287-ede733891605',
                compensationMultiplier: 1,
                flsaStatus: 'Exempt',
              },
            ],
            paidTimeOff: [
              {
                name: 'Vacation Hours',
                hours: '0.0',
              },
              {
                name: 'Sick Hours',
                hours: '0.0',
              },
              {
                name: 'Holiday Hours',
                hours: '0.0',
              },
            ],
            taxes: [
              {
                name: 'Federal Income Tax',
                employer: false,
                amount: 168.73,
              },
              {
                name: 'Social Security',
                employer: false,
                amount: 93,
              },
              {
                name: 'Social Security',
                employer: true,
                amount: 93,
              },
              {
                name: 'Medicare',
                employer: false,
                amount: 21.75,
              },
              {
                name: 'Medicare',
                employer: true,
                amount: 21.75,
              },
              {
                name: 'CA State Income Tax',
                employer: false,
                amount: 66.26,
              },
              {
                name: 'FUTA',
                employer: true,
                amount: 9,
              },
              {
                name: 'CA SUI',
                employer: true,
                amount: 51,
              },
              {
                name: 'CA SDI',
                employer: false,
                amount: 18,
              },
              {
                name: 'CA ETT',
                employer: true,
                amount: 1.5,
              },
            ],
            benefits: [],
            deductions: [],
          },
          {
            employeeUuid: '07684391-0dc7-433d-bd3c-7bbbff69df16',
            excluded: false,
            version: '6d46c042cbb2e7cfc2cb9ba97d22ca23',
            grossPay: 1346.15,
            netPay: 1039.93,
            checkAmount: 1039.93,
            paymentMethod: 'Direct Deposit',
            memo: null,
            fixedCompensations: [],
            hourlyCompensations: [
              {
                name: 'Regular Hours',
                hours: '20.000',
                amount: '1346.15',
                jobUuid: 'b9cea817-e56c-459d-b29a-047be8280e29',
                compensationMultiplier: 1,
                flsaStatus: 'Exempt',
              },
            ],
            paidTimeOff: [
              {
                name: 'Vacation Hours',
                hours: '0.0',
              },
              {
                name: 'Sick Hours',
                hours: '0.0',
              },
              {
                name: 'Holiday Hours',
                hours: '0.0',
              },
            ],
            taxes: [
              {
                name: 'Federal Income Tax',
                employer: false,
                amount: 134.88,
              },
              {
                name: 'Social Security',
                employer: false,
                amount: 83.46,
              },
              {
                name: 'Social Security',
                employer: true,
                amount: 83.46,
              },
              {
                name: 'Medicare',
                employer: false,
                amount: 19.52,
              },
              {
                name: 'Medicare',
                employer: true,
                amount: 19.52,
              },
              {
                name: 'CA State Income Tax',
                employer: false,
                amount: 52.21,
              },
              {
                name: 'FUTA',
                employer: true,
                amount: 8.08,
              },
              {
                name: 'CA SUI',
                employer: true,
                amount: 45.77,
              },
              {
                name: 'CA SDI',
                employer: false,
                amount: 16.15,
              },
              {
                name: 'CA ETT',
                employer: true,
                amount: 1.35,
              },
            ],
            benefits: [],
            deductions: [],
          },
          {
            employeeUuid: '3b7c6f7c-fdde-443b-9aee-f65757da44f0',
            excluded: false,
            version: '54bd6765073252071fe6f31c88b39245',
            grossPay: 1173.08,
            netPay: 930.54,
            checkAmount: 930.54,
            paymentMethod: 'Direct Deposit',
            memo: null,
            fixedCompensations: [],
            hourlyCompensations: [
              {
                name: 'Regular Hours',
                hours: '20.000',
                amount: '1173.08',
                jobUuid: '8cbba341-43a0-42dd-a1e2-5e9c448bcb5f',
                compensationMultiplier: 1,
                flsaStatus: 'Exempt',
              },
            ],
            paidTimeOff: [
              {
                name: 'Vacation Hours',
                hours: '0.0',
              },
              {
                name: 'Sick Hours',
                hours: '0.0',
              },
              {
                name: 'Holiday Hours',
                hours: '0.0',
              },
            ],
            taxes: [
              {
                name: 'Federal Income Tax',
                employer: false,
                amount: 101.57,
              },
              {
                name: 'Social Security',
                employer: false,
                amount: 72.73,
              },
              {
                name: 'Social Security',
                employer: true,
                amount: 72.73,
              },
              {
                name: 'Medicare',
                employer: false,
                amount: 17.01,
              },
              {
                name: 'Medicare',
                employer: true,
                amount: 17.01,
              },
              {
                name: 'CA State Income Tax',
                employer: false,
                amount: 37.15,
              },
              {
                name: 'FUTA',
                employer: true,
                amount: 7.04,
              },
              {
                name: 'CA SUI',
                employer: true,
                amount: 39.88,
              },
              {
                name: 'CA SDI',
                employer: false,
                amount: 14.08,
              },
              {
                name: 'CA ETT',
                employer: true,
                amount: 1.17,
              },
            ],
            benefits: [],
            deductions: [],
          },
          {
            employeeUuid: '1563def5-6a6a-463e-b1c2-be746926662e',
            excluded: false,
            version: '1e9a1215f64c5d619da47d5e22ba5e68',
            grossPay: 2115.38,
            netPay: 1494.84,
            checkAmount: 1494.84,
            paymentMethod: 'Direct Deposit',
            memo: null,
            fixedCompensations: [],
            hourlyCompensations: [
              {
                name: 'Regular Hours',
                hours: '20.000',
                amount: '2115.38',
                jobUuid: '77ef4fe3-242c-4b70-8ff9-5e16ff2ac727',
                compensationMultiplier: 1,
                flsaStatus: 'Exempt',
              },
            ],
            paidTimeOff: [
              {
                name: 'Vacation Hours',
                hours: '0.0',
              },
              {
                name: 'Sick Hours',
                hours: '0.0',
              },
              {
                name: 'Holiday Hours',
                hours: '0.0',
              },
            ],
            taxes: [
              {
                name: 'Federal Income Tax',
                employer: false,
                amount: 304.11,
              },
              {
                name: 'Social Security',
                employer: false,
                amount: 131.16,
              },
              {
                name: 'Social Security',
                employer: true,
                amount: 131.16,
              },
              {
                name: 'Medicare',
                employer: false,
                amount: 30.68,
              },
              {
                name: 'Medicare',
                employer: true,
                amount: 30.68,
              },
              {
                name: 'CA State Income Tax',
                employer: false,
                amount: 129.21,
              },
              {
                name: 'FUTA',
                employer: true,
                amount: 12.69,
              },
              {
                name: 'CA SUI',
                employer: true,
                amount: 71.92,
              },
              {
                name: 'CA SDI',
                employer: false,
                amount: 25.38,
              },
              {
                name: 'CA ETT',
                employer: true,
                amount: 2.12,
              },
            ],
            benefits: [],
            deductions: [],
          },
          {
            employeeUuid: '0a5a4dc1-e1c1-4825-9cf2-8717397c5977',
            excluded: false,
            version: '92a1c9d8f72c3cbff9bdeab2f1e883e7',
            grossPay: 2115.38,
            netPay: 1494.84,
            checkAmount: 1494.84,
            paymentMethod: 'Direct Deposit',
            memo: null,
            fixedCompensations: [],
            hourlyCompensations: [
              {
                name: 'Regular Hours',
                hours: '20.000',
                amount: '2115.38',
                jobUuid: '9bf4f52b-0592-40bc-8ab5-c0616979c54d',
                compensationMultiplier: 1,
                flsaStatus: 'Exempt',
              },
            ],
            paidTimeOff: [
              {
                name: 'Vacation Hours',
                hours: '0.0',
              },
              {
                name: 'Sick Hours',
                hours: '0.0',
              },
              {
                name: 'Holiday Hours',
                hours: '0.0',
              },
            ],
            taxes: [
              {
                name: 'Federal Income Tax',
                employer: false,
                amount: 304.11,
              },
              {
                name: 'Social Security',
                employer: false,
                amount: 131.16,
              },
              {
                name: 'Social Security',
                employer: true,
                amount: 131.16,
              },
              {
                name: 'Medicare',
                employer: false,
                amount: 30.68,
              },
              {
                name: 'Medicare',
                employer: true,
                amount: 30.68,
              },
              {
                name: 'CA State Income Tax',
                employer: false,
                amount: 129.21,
              },
              {
                name: 'FUTA',
                employer: true,
                amount: 12.69,
              },
              {
                name: 'CA SUI',
                employer: true,
                amount: 71.92,
              },
              {
                name: 'CA SDI',
                employer: false,
                amount: 25.38,
              },
              {
                name: 'CA ETT',
                employer: true,
                amount: 2.12,
              },
            ],
            benefits: [],
            deductions: [],
          },
          {
            employeeUuid: '07192709-2dee-4db8-9f99-b5ea5abdd82c',
            excluded: false,
            version: '3e6e9feab3f8402faab4a078e2faa97c',
            grossPay: 440,
            netPay: 384,
            checkAmount: 384,
            paymentMethod: 'Direct Deposit',
            memo: null,
            fixedCompensations: [],
            hourlyCompensations: [
              {
                name: 'Regular Hours',
                hours: '20.000',
                amount: '440.0',
                jobUuid: '41bcabdb-42d0-411c-bee0-24b547a4ad08',
                compensationMultiplier: 1,
                flsaStatus: 'Nonexempt',
              },
            ],
            paidTimeOff: [
              {
                name: 'Vacation Hours',
                hours: '0.0',
              },
              {
                name: 'Sick Hours',
                hours: '0.0',
              },
              {
                name: 'Holiday Hours',
                hours: '0.0',
              },
            ],
            taxes: [
              {
                name: 'Federal Income Tax',
                employer: false,
                amount: 15.15,
              },
              {
                name: 'Social Security',
                employer: false,
                amount: 27.28,
              },
              {
                name: 'Social Security',
                employer: true,
                amount: 27.28,
              },
              {
                name: 'Medicare',
                employer: false,
                amount: 6.38,
              },
              {
                name: 'Medicare',
                employer: true,
                amount: 6.38,
              },
              {
                name: 'CA State Income Tax',
                employer: false,
                amount: 1.91,
              },
              {
                name: 'FUTA',
                employer: true,
                amount: 2.64,
              },
              {
                name: 'CA SUI',
                employer: true,
                amount: 14.96,
              },
              {
                name: 'CA SDI',
                employer: false,
                amount: 5.28,
              },
              {
                name: 'CA ETT',
                employer: true,
                amount: 0.44,
              },
            ],
            benefits: [],
            deductions: [],
          },
          {
            employeeUuid: '9bb707ae-a296-4071-b933-013cd6162bb7',
            excluded: false,
            version: '07c4f87425270ae54ff901e1df6accea',
            grossPay: 1538.46,
            netPay: 1154.92,
            checkAmount: 1154.92,
            paymentMethod: 'Direct Deposit',
            memo: null,
            fixedCompensations: [],
            hourlyCompensations: [
              {
                name: 'Regular Hours',
                hours: '20.000',
                amount: '1538.46',
                jobUuid: 'd296ce91-6b8c-42eb-a456-19f8d90caf68',
                compensationMultiplier: 1,
                flsaStatus: 'Exempt',
              },
            ],
            paidTimeOff: [
              {
                name: 'Vacation Hours',
                hours: '0.0',
              },
              {
                name: 'Sick Hours',
                hours: '0.0',
              },
              {
                name: 'Holiday Hours',
                hours: '0.0',
              },
            ],
            taxes: [
              {
                name: 'Federal Income Tax',
                employer: false,
                amount: 177.19,
              },
              {
                name: 'Social Security',
                employer: false,
                amount: 95.39,
              },
              {
                name: 'Social Security',
                employer: true,
                amount: 95.39,
              },
              {
                name: 'Medicare',
                employer: false,
                amount: 22.31,
              },
              {
                name: 'Medicare',
                employer: true,
                amount: 22.31,
              },
              {
                name: 'CA State Income Tax',
                employer: false,
                amount: 70.19,
              },
              {
                name: 'FUTA',
                employer: true,
                amount: 9.23,
              },
              {
                name: 'CA SUI',
                employer: true,
                amount: 52.31,
              },
              {
                name: 'CA SDI',
                employer: false,
                amount: 18.46,
              },
              {
                name: 'CA ETT',
                employer: true,
                amount: 1.54,
              },
            ],
            benefits: [],
            deductions: [],
          },
          {
            employeeUuid: '89540375-9ac7-4dc7-9c05-0e8cf14c1633',
            excluded: false,
            version: '94ff40d02a05c159ea4710df95d513e2',
            grossPay: 846.15,
            netPay: 692.6,
            checkAmount: 692.6,
            paymentMethod: 'Direct Deposit',
            memo: null,
            fixedCompensations: [],
            hourlyCompensations: [
              {
                name: 'Regular Hours',
                hours: '20.000',
                amount: '846.15',
                jobUuid: '3716981a-fd79-44bb-b3af-04abf2b4a88c',
                compensationMultiplier: 1,
                flsaStatus: 'Nonexempt',
              },
            ],
            paidTimeOff: [
              {
                name: 'Vacation Hours',
                hours: '0.0',
              },
              {
                name: 'Sick Hours',
                hours: '0.0',
              },
              {
                name: 'Holiday Hours',
                hours: '0.0',
              },
            ],
            taxes: [
              {
                name: 'Federal Income Tax',
                employer: false,
                amount: 62.34,
              },
              {
                name: 'Social Security',
                employer: false,
                amount: 52.46,
              },
              {
                name: 'Social Security',
                employer: true,
                amount: 52.46,
              },
              {
                name: 'Medicare',
                employer: false,
                amount: 12.27,
              },
              {
                name: 'Medicare',
                employer: true,
                amount: 12.27,
              },
              {
                name: 'CA State Income Tax',
                employer: false,
                amount: 16.33,
              },
              {
                name: 'FUTA',
                employer: true,
                amount: 5.08,
              },
              {
                name: 'CA SUI',
                employer: true,
                amount: 28.77,
              },
              {
                name: 'CA SDI',
                employer: false,
                amount: 10.15,
              },
              {
                name: 'CA ETT',
                employer: true,
                amount: 0.85,
              },
            ],
            benefits: [],
            deductions: [],
          },
          {
            employeeUuid: '8e9c8d3d-ce5c-4822-bd27-f197719c1009',
            excluded: false,
            version: '52941bd9a9ad2614c9a6ca303728fd54',
            grossPay: 1500,
            netPay: 1132.26,
            checkAmount: 1132.26,
            paymentMethod: 'Direct Deposit',
            memo: null,
            fixedCompensations: [],
            hourlyCompensations: [
              {
                name: 'Regular Hours',
                hours: '20.000',
                amount: '1500.0',
                jobUuid: '589bfc17-cbfe-4ad2-84b4-425f5ffe548f',
                compensationMultiplier: 1,
                flsaStatus: 'Exempt',
              },
            ],
            paidTimeOff: [
              {
                name: 'Vacation Hours',
                hours: '0.0',
              },
              {
                name: 'Sick Hours',
                hours: '0.0',
              },
              {
                name: 'Holiday Hours',
                hours: '0.0',
              },
            ],
            taxes: [
              {
                name: 'Federal Income Tax',
                employer: false,
                amount: 168.73,
              },
              {
                name: 'Social Security',
                employer: false,
                amount: 93,
              },
              {
                name: 'Social Security',
                employer: true,
                amount: 93,
              },
              {
                name: 'Medicare',
                employer: false,
                amount: 21.75,
              },
              {
                name: 'Medicare',
                employer: true,
                amount: 21.75,
              },
              {
                name: 'CA State Income Tax',
                employer: false,
                amount: 66.26,
              },
              {
                name: 'FUTA',
                employer: true,
                amount: 9,
              },
              {
                name: 'CA SUI',
                employer: true,
                amount: 51,
              },
              {
                name: 'CA SDI',
                employer: false,
                amount: 18,
              },
              {
                name: 'CA ETT',
                employer: true,
                amount: 1.5,
              },
            ],
            benefits: [],
            deductions: [],
          },
          {
            employeeUuid: '2849b9e2-83c2-46b1-9c10-a127da02d117',
            excluded: false,
            version: '2baa71ffc54c15077bbda66faa50e3e9',
            grossPay: 740,
            netPay: 613.25,
            checkAmount: 613.25,
            paymentMethod: 'Direct Deposit',
            memo: null,
            fixedCompensations: [],
            hourlyCompensations: [
              {
                name: 'Regular Hours',
                hours: '20.000',
                amount: '740.0',
                jobUuid: '4bbc8b1e-4c98-4be5-9a99-32c4ad6b0e7c',
                compensationMultiplier: 1,
                flsaStatus: 'Nonexempt',
              },
            ],
            paidTimeOff: [
              {
                name: 'Vacation Hours',
                hours: '0.0',
              },
              {
                name: 'Sick Hours',
                hours: '0.0',
              },
              {
                name: 'Holiday Hours',
                hours: '0.0',
              },
            ],
            taxes: [
              {
                name: 'Federal Income Tax',
                employer: false,
                amount: 49.6,
              },
              {
                name: 'Social Security',
                employer: false,
                amount: 45.88,
              },
              {
                name: 'Social Security',
                employer: true,
                amount: 45.88,
              },
              {
                name: 'Medicare',
                employer: false,
                amount: 10.73,
              },
              {
                name: 'Medicare',
                employer: true,
                amount: 10.73,
              },
              {
                name: 'CA State Income Tax',
                employer: false,
                amount: 11.66,
              },
              {
                name: 'FUTA',
                employer: true,
                amount: 4.44,
              },
              {
                name: 'CA SUI',
                employer: true,
                amount: 25.16,
              },
              {
                name: 'CA SDI',
                employer: false,
                amount: 8.88,
              },
              {
                name: 'CA ETT',
                employer: true,
                amount: 0.74,
              },
            ],
            benefits: [],
            deductions: [],
          },
        ],
      }}
      employeeDetails={[
        {
          uuid: '7aef801c-19e3-469c-a8b3-ce3437f9b88f',
          firstName: 'Isaiah',
          middleInitial: null,
          lastName: 'Berlin',
          email: 'iberlin661013@initech.biz',
          companyUuid: '624e94a3-da0a-48e1-9f9b-667f8d502ce1',
          managerUuid: '07684391-0dc7-433d-bd3c-7bbbff69df16',
          version: 'aabf2bbebf3f5c36b9950487b34748f8',
          department: 'Sales',
          terminated: false,
          twoPercentShareholder: false,
          workEmail: null,
          onboarded: true,
          onboardingStatus: 'onboarding_completed',
          onboardingDocumentsConfig: {
            uuid: null,
            i9Document: false,
          },
          jobs: [
            {
              uuid: '3834f43e-3905-4690-869b-5e9b4dd4b613',
              version: '652a4cc3cfbd33ac7670f5210fbc626a',
              employeeUuid: '7aef801c-19e3-469c-a8b3-ce3437f9b88f',
              hireDate: '2024-08-14',
              title: 'Client Support Manager',
              primary: true,
              rate: '22.00',
              paymentUnit: 'Hour',
              currentCompensationUuid: '1b2a4bd8-b440-4e5c-a008-e84fb4c7f111',
              twoPercentShareholder: false,
              stateWcCovered: null,
              stateWcClassCode: null,
              compensations: [
                {
                  uuid: '1b2a4bd8-b440-4e5c-a008-e84fb4c7f111',
                  version: '1a4a62a51b862106bd825868e200196c',
                  jobUuid: '3834f43e-3905-4690-869b-5e9b4dd4b613',
                  employeeUuid: '7aef801c-19e3-469c-a8b3-ce3437f9b88f',
                  rate: '22.00',
                  paymentUnit: 'Hour',
                  flsaStatus: 'Nonexempt',
                  effectiveDate: '2025-08-14',
                  adjustForMinimumWage: false,
                  minimumWages: [],
                },
              ],
            },
          ],
          eligiblePaidTimeOff: [
            {
              name: 'Sick Hours',
              policyName: 'Sick Policy',
              policyUuid: '8052b584-c0ff-4fd5-90ed-7173a5f35c28',
              accrualUnit: 'Hour',
              accrualRate: '208.0',
              accrualMethod: 'per_hour_worked',
              accrualPeriod: 'Year',
              accrualBalance: '26.0',
              maximumAccrualBalance: '240.0',
              paidAtTermination: false,
            },
            {
              name: 'Vacation Hours',
              policyName: 'Paid Time Off Policy',
              policyUuid: 'fb908fc7-c75f-4624-8ec4-106c1b146fc1',
              accrualUnit: 'Hour',
              accrualRate: '208.0',
              accrualMethod: 'per_hour_worked',
              accrualPeriod: 'Year',
              accrualBalance: '54.0',
              maximumAccrualBalance: '240.0',
              paidAtTermination: true,
            },
          ],
          terminations: [],
          garnishments: [],
          dateOfBirth: '1998-08-14',
          hasSsn: true,
          ssn: '',
          phone: null,
          preferredFirstName: null,
          paymentMethod: 'Direct Deposit',
          currentEmploymentStatus: 'full_time',
          historical: false,
          employeeCode: '187475',
          departmentUuid: '2dd0e2c3-2f0f-4c30-9dd8-f2a42c56ae28',
        },
        {
          uuid: 'd73de8ef-a54c-4979-a4d6-f1c64a13963b',
          firstName: 'Patricia',
          middleInitial: null,
          lastName: 'Churchland',
          email: 'churchland661013@initech.biz',
          companyUuid: '624e94a3-da0a-48e1-9f9b-667f8d502ce1',
          managerUuid: '0a5a4dc1-e1c1-4825-9cf2-8717397c5977',
          version: '2c62a8af69d7c580eaed6dccb17fb485',
          department: 'Sales',
          terminated: false,
          twoPercentShareholder: false,
          workEmail: null,
          onboarded: true,
          onboardingStatus: 'onboarding_completed',
          onboardingDocumentsConfig: {
            uuid: null,
            i9Document: false,
          },
          jobs: [
            {
              uuid: 'd1d6b37c-1335-403f-8287-ede733891605',
              version: '6649b968b36e0d8eac5ddb68d732faf8',
              employeeUuid: 'd73de8ef-a54c-4979-a4d6-f1c64a13963b',
              hireDate: '2024-08-14',
              title: 'Account Director',
              primary: true,
              rate: '78000.00',
              paymentUnit: 'Year',
              currentCompensationUuid: '0f517602-955f-4f89-bc05-cac07af81c55',
              twoPercentShareholder: false,
              stateWcCovered: null,
              stateWcClassCode: null,
              compensations: [
                {
                  uuid: '0f517602-955f-4f89-bc05-cac07af81c55',
                  version: 'cdbaad910726422eb5170975b77d1e86',
                  jobUuid: 'd1d6b37c-1335-403f-8287-ede733891605',
                  employeeUuid: 'd73de8ef-a54c-4979-a4d6-f1c64a13963b',
                  rate: '78000.00',
                  paymentUnit: 'Year',
                  flsaStatus: 'Exempt',
                  effectiveDate: '2025-08-14',
                  adjustForMinimumWage: false,
                  minimumWages: [],
                },
              ],
            },
          ],
          eligiblePaidTimeOff: [
            {
              name: 'Sick Hours',
              policyName: 'Sick Policy',
              policyUuid: '8052b584-c0ff-4fd5-90ed-7173a5f35c28',
              accrualUnit: 'Hour',
              accrualRate: '208.0',
              accrualMethod: 'per_hour_worked',
              accrualPeriod: 'Year',
              accrualBalance: '25.0',
              maximumAccrualBalance: '240.0',
              paidAtTermination: false,
            },
            {
              name: 'Vacation Hours',
              policyName: 'Paid Time Off Policy',
              policyUuid: 'fb908fc7-c75f-4624-8ec4-106c1b146fc1',
              accrualUnit: 'Hour',
              accrualRate: '208.0',
              accrualMethod: 'per_hour_worked',
              accrualPeriod: 'Year',
              accrualBalance: '19.0',
              maximumAccrualBalance: '240.0',
              paidAtTermination: true,
            },
          ],
          terminations: [],
          garnishments: [],
          dateOfBirth: '1992-08-14',
          hasSsn: true,
          ssn: '',
          phone: null,
          preferredFirstName: null,
          paymentMethod: 'Direct Deposit',
          currentEmploymentStatus: 'full_time',
          historical: false,
          employeeCode: '945a85',
          departmentUuid: '2dd0e2c3-2f0f-4c30-9dd8-f2a42c56ae28',
        },
        {
          uuid: '07684391-0dc7-433d-bd3c-7bbbff69df16',
          firstName: 'Soren',
          middleInitial: null,
          lastName: 'Kierkegaard',
          email: 'kierkegaard661013@initech.biz',
          companyUuid: '624e94a3-da0a-48e1-9f9b-667f8d502ce1',
          managerUuid: '0a5a4dc1-e1c1-4825-9cf2-8717397c5977',
          version: '2a3125eb73da0e276538c044c5b47e65',
          department: 'Marketing',
          terminated: false,
          twoPercentShareholder: false,
          workEmail: null,
          onboarded: true,
          onboardingStatus: 'onboarding_completed',
          onboardingDocumentsConfig: {
            uuid: null,
            i9Document: false,
          },
          jobs: [
            {
              uuid: 'b9cea817-e56c-459d-b29a-047be8280e29',
              version: '5ea2d5951e9c144da8287b171472a6a3',
              employeeUuid: '07684391-0dc7-433d-bd3c-7bbbff69df16',
              hireDate: '2024-08-14',
              title: 'Client Support Director',
              primary: true,
              rate: '70000.00',
              paymentUnit: 'Year',
              currentCompensationUuid: '119aea35-c6bb-48cc-8441-bb6394d858cf',
              twoPercentShareholder: false,
              stateWcCovered: null,
              stateWcClassCode: null,
              compensations: [
                {
                  uuid: '119aea35-c6bb-48cc-8441-bb6394d858cf',
                  version: 'efca8e703c20feb4f67fd34b542c65a6',
                  jobUuid: 'b9cea817-e56c-459d-b29a-047be8280e29',
                  employeeUuid: '07684391-0dc7-433d-bd3c-7bbbff69df16',
                  rate: '70000.00',
                  paymentUnit: 'Year',
                  flsaStatus: 'Exempt',
                  effectiveDate: '2025-08-14',
                  adjustForMinimumWage: false,
                  minimumWages: [],
                },
              ],
            },
          ],
          eligiblePaidTimeOff: [],
          terminations: [],
          garnishments: [],
          dateOfBirth: '1994-08-14',
          hasSsn: true,
          ssn: '',
          phone: null,
          preferredFirstName: null,
          paymentMethod: 'Direct Deposit',
          currentEmploymentStatus: 'full_time',
          historical: false,
          employeeCode: '812a8b',
          departmentUuid: '2780ba56-0e90-4402-8c07-c2f7256826b7',
        },
        {
          uuid: '3b7c6f7c-fdde-443b-9aee-f65757da44f0',
          firstName: 'Hannah',
          middleInitial: null,
          lastName: 'Arendt',
          email: 'arendt661013@initech.biz',
          companyUuid: '624e94a3-da0a-48e1-9f9b-667f8d502ce1',
          managerUuid: 'd73de8ef-a54c-4979-a4d6-f1c64a13963b',
          version: '3413f84b86b8e3616c24b9540993ee9b',
          department: 'Marketing',
          terminated: false,
          twoPercentShareholder: false,
          workEmail: null,
          onboarded: true,
          onboardingStatus: 'onboarding_completed',
          onboardingDocumentsConfig: {
            uuid: null,
            i9Document: false,
          },
          jobs: [
            {
              uuid: '8cbba341-43a0-42dd-a1e2-5e9c448bcb5f',
              version: '1d930e909ef61b1d45c681d4c0d26bc6',
              employeeUuid: '3b7c6f7c-fdde-443b-9aee-f65757da44f0',
              hireDate: '2024-08-14',
              title: 'Account Manager',
              primary: true,
              rate: '61000.00',
              paymentUnit: 'Year',
              currentCompensationUuid: 'e4bdc122-8240-42b5-a4de-8d40ac6e4a25',
              twoPercentShareholder: false,
              stateWcCovered: null,
              stateWcClassCode: null,
              compensations: [
                {
                  uuid: 'e4bdc122-8240-42b5-a4de-8d40ac6e4a25',
                  version: '9965201362509d60b06c238838aca675',
                  jobUuid: '8cbba341-43a0-42dd-a1e2-5e9c448bcb5f',
                  employeeUuid: '3b7c6f7c-fdde-443b-9aee-f65757da44f0',
                  rate: '61000.00',
                  paymentUnit: 'Year',
                  flsaStatus: 'Exempt',
                  effectiveDate: '2025-08-14',
                  adjustForMinimumWage: false,
                  minimumWages: [],
                },
              ],
            },
          ],
          eligiblePaidTimeOff: [],
          terminations: [],
          garnishments: [],
          dateOfBirth: '1974-08-14',
          hasSsn: true,
          ssn: '',
          phone: null,
          preferredFirstName: null,
          paymentMethod: 'Direct Deposit',
          currentEmploymentStatus: 'full_time',
          historical: false,
          employeeCode: 'dd8cd4',
          departmentUuid: '2780ba56-0e90-4402-8c07-c2f7256826b7',
        },
        {
          uuid: '1563def5-6a6a-463e-b1c2-be746926662e',
          firstName: 'Taylor',
          middleInitial: null,
          lastName: 'Swift',
          email: 'taylaswiff661013@taylornation.biz',
          companyUuid: '624e94a3-da0a-48e1-9f9b-667f8d502ce1',
          managerUuid: '0a5a4dc1-e1c1-4825-9cf2-8717397c5977',
          version: '76c8f652b3a57cd886b7a4e789bde569',
          department: 'Engineering',
          terminated: false,
          twoPercentShareholder: false,
          workEmail: null,
          onboarded: true,
          onboardingStatus: 'onboarding_completed',
          onboardingDocumentsConfig: {
            uuid: null,
            i9Document: false,
          },
          jobs: [
            {
              uuid: '77ef4fe3-242c-4b70-8ff9-5e16ff2ac727',
              version: 'ef1c3354412bfd4cf6ff6cf7fd21403f',
              employeeUuid: '1563def5-6a6a-463e-b1c2-be746926662e',
              hireDate: '2024-08-14',
              title: 'CTO',
              primary: true,
              rate: '110000.00',
              paymentUnit: 'Year',
              currentCompensationUuid: 'bb0de205-9ef7-486f-aaf1-edc9097f0909',
              twoPercentShareholder: false,
              stateWcCovered: null,
              stateWcClassCode: null,
              compensations: [
                {
                  uuid: 'bb0de205-9ef7-486f-aaf1-edc9097f0909',
                  version: '685ad94309ec881b29003b2fd529598f',
                  jobUuid: '77ef4fe3-242c-4b70-8ff9-5e16ff2ac727',
                  employeeUuid: '1563def5-6a6a-463e-b1c2-be746926662e',
                  rate: '110000.00',
                  paymentUnit: 'Year',
                  flsaStatus: 'Exempt',
                  effectiveDate: '2025-08-14',
                  adjustForMinimumWage: false,
                  minimumWages: [],
                },
              ],
            },
          ],
          eligiblePaidTimeOff: [],
          terminations: [],
          garnishments: [],
          dateOfBirth: '1989-12-13',
          hasSsn: true,
          ssn: '',
          phone: null,
          preferredFirstName: null,
          paymentMethod: 'Direct Deposit',
          currentEmploymentStatus: 'full_time',
          historical: false,
          employeeCode: 'f0b042',
          departmentUuid: 'ee2bcaaf-faf3-4813-97d7-873b72692b61',
        },
        {
          uuid: '0a5a4dc1-e1c1-4825-9cf2-8717397c5977',
          firstName: 'Regina',
          middleInitial: null,
          lastName: 'Spektor',
          email: 'spektor661013@initech.biz',
          companyUuid: '624e94a3-da0a-48e1-9f9b-667f8d502ce1',
          managerUuid: null,
          version: '05a852087fc19b1ee8239b77b73374d5',
          department: 'Engineering',
          terminated: false,
          twoPercentShareholder: false,
          workEmail: null,
          onboarded: true,
          onboardingStatus: 'onboarding_completed',
          onboardingDocumentsConfig: {
            uuid: null,
            i9Document: false,
          },
          jobs: [
            {
              uuid: '9bf4f52b-0592-40bc-8ab5-c0616979c54d',
              version: 'd0c1330609a9a6761544fc2a6e55061b',
              employeeUuid: '0a5a4dc1-e1c1-4825-9cf2-8717397c5977',
              hireDate: '2024-08-14',
              title: 'CEO',
              primary: true,
              rate: '110000.00',
              paymentUnit: 'Year',
              currentCompensationUuid: 'b9191259-aa9a-4551-b9e4-aca804e3feb6',
              twoPercentShareholder: false,
              stateWcCovered: null,
              stateWcClassCode: null,
              compensations: [
                {
                  uuid: 'b9191259-aa9a-4551-b9e4-aca804e3feb6',
                  version: '581a41e3706b68fc2a4c60a7225a6dfc',
                  jobUuid: '9bf4f52b-0592-40bc-8ab5-c0616979c54d',
                  employeeUuid: '0a5a4dc1-e1c1-4825-9cf2-8717397c5977',
                  rate: '110000.00',
                  paymentUnit: 'Year',
                  flsaStatus: 'Exempt',
                  effectiveDate: '2025-08-14',
                  adjustForMinimumWage: false,
                  minimumWages: [],
                },
              ],
            },
          ],
          eligiblePaidTimeOff: [],
          terminations: [],
          garnishments: [],
          dateOfBirth: '1986-08-14',
          hasSsn: true,
          ssn: '',
          phone: null,
          preferredFirstName: null,
          paymentMethod: 'Direct Deposit',
          currentEmploymentStatus: 'full_time',
          historical: false,
          employeeCode: '43c021',
          departmentUuid: 'ee2bcaaf-faf3-4813-97d7-873b72692b61',
        },
        {
          uuid: '07192709-2dee-4db8-9f99-b5ea5abdd82c',
          firstName: 'Immanuel',
          middleInitial: null,
          lastName: 'Kant',
          email: 'kant661013@initech.biz',
          companyUuid: '624e94a3-da0a-48e1-9f9b-667f8d502ce1',
          managerUuid: '07684391-0dc7-433d-bd3c-7bbbff69df16',
          version: '0059c49385034a32e8df65ee970a02dd',
          department: 'Engineering',
          terminated: false,
          twoPercentShareholder: false,
          workEmail: null,
          onboarded: true,
          onboardingStatus: 'onboarding_completed',
          onboardingDocumentsConfig: {
            uuid: null,
            i9Document: false,
          },
          jobs: [
            {
              uuid: '41bcabdb-42d0-411c-bee0-24b547a4ad08',
              version: '652a4cc3cfbd33ac7670f5210fbc626a',
              employeeUuid: '07192709-2dee-4db8-9f99-b5ea5abdd82c',
              hireDate: '2024-08-14',
              title: 'Client Support Manager',
              primary: true,
              rate: '22.00',
              paymentUnit: 'Hour',
              currentCompensationUuid: 'f0d80c20-5c88-4df0-a572-a6c26afb96c1',
              twoPercentShareholder: false,
              stateWcCovered: null,
              stateWcClassCode: null,
              compensations: [
                {
                  uuid: 'f0d80c20-5c88-4df0-a572-a6c26afb96c1',
                  version: '1a4a62a51b862106bd825868e200196c',
                  jobUuid: '41bcabdb-42d0-411c-bee0-24b547a4ad08',
                  employeeUuid: '07192709-2dee-4db8-9f99-b5ea5abdd82c',
                  rate: '22.00',
                  paymentUnit: 'Hour',
                  flsaStatus: 'Nonexempt',
                  effectiveDate: '2025-08-14',
                  adjustForMinimumWage: false,
                  minimumWages: [],
                },
              ],
            },
          ],
          eligiblePaidTimeOff: [],
          terminations: [],
          garnishments: [],
          dateOfBirth: '1981-08-14',
          hasSsn: true,
          ssn: '',
          phone: null,
          preferredFirstName: null,
          paymentMethod: 'Direct Deposit',
          currentEmploymentStatus: 'full_time',
          historical: false,
          employeeCode: 'd41ece',
          departmentUuid: 'ee2bcaaf-faf3-4813-97d7-873b72692b61',
        },
        {
          uuid: '9bb707ae-a296-4071-b933-013cd6162bb7',
          firstName: 'Friedrich',
          middleInitial: null,
          lastName: 'Nietzsche',
          email: 'nietzsche661013@initech.biz',
          companyUuid: '624e94a3-da0a-48e1-9f9b-667f8d502ce1',
          managerUuid: '1563def5-6a6a-463e-b1c2-be746926662e',
          version: '58bd7f9a7d9899f5307235e53872653c',
          department: 'Engineering',
          terminated: false,
          twoPercentShareholder: false,
          workEmail: null,
          onboarded: true,
          onboardingStatus: 'onboarding_completed',
          onboardingDocumentsConfig: {
            uuid: null,
            i9Document: false,
          },
          jobs: [
            {
              uuid: 'd296ce91-6b8c-42eb-a456-19f8d90caf68',
              version: 'b129f05b327849e2e3169fc2930d02dd',
              employeeUuid: '9bb707ae-a296-4071-b933-013cd6162bb7',
              hireDate: '2024-08-14',
              title: 'Engineer',
              primary: true,
              rate: '80000.00',
              paymentUnit: 'Year',
              currentCompensationUuid: 'f6110d44-ecd3-4c92-9076-39c113578f9b',
              twoPercentShareholder: false,
              stateWcCovered: null,
              stateWcClassCode: null,
              compensations: [
                {
                  uuid: 'f6110d44-ecd3-4c92-9076-39c113578f9b',
                  version: 'f83658e34cec6c5d3d9aa877f2909834',
                  jobUuid: 'd296ce91-6b8c-42eb-a456-19f8d90caf68',
                  employeeUuid: '9bb707ae-a296-4071-b933-013cd6162bb7',
                  rate: '80000.00',
                  paymentUnit: 'Year',
                  flsaStatus: 'Exempt',
                  effectiveDate: '2025-08-14',
                  adjustForMinimumWage: false,
                  minimumWages: [],
                },
              ],
            },
          ],
          eligiblePaidTimeOff: [],
          terminations: [],
          garnishments: [],
          dateOfBirth: '1972-08-14',
          hasSsn: true,
          ssn: '',
          phone: null,
          preferredFirstName: null,
          paymentMethod: 'Direct Deposit',
          currentEmploymentStatus: 'full_time',
          historical: false,
          employeeCode: '546545',
          departmentUuid: 'ee2bcaaf-faf3-4813-97d7-873b72692b61',
        },
        {
          uuid: '89540375-9ac7-4dc7-9c05-0e8cf14c1633',
          firstName: 'Arthur',
          middleInitial: null,
          lastName: 'Schopenhauer',
          email: 'schopenhauer661013@initech.biz',
          companyUuid: '624e94a3-da0a-48e1-9f9b-667f8d502ce1',
          managerUuid: '1563def5-6a6a-463e-b1c2-be746926662e',
          version: '318c3dec788cf6a437b56a7cbce813bf',
          department: 'Engineering',
          terminated: false,
          twoPercentShareholder: false,
          workEmail: null,
          onboarded: true,
          onboardingStatus: 'onboarding_completed',
          onboardingDocumentsConfig: {
            uuid: null,
            i9Document: false,
          },
          jobs: [
            {
              uuid: '3716981a-fd79-44bb-b3af-04abf2b4a88c',
              version: '66715cef9902066320976d655ce52662',
              employeeUuid: '89540375-9ac7-4dc7-9c05-0e8cf14c1633',
              hireDate: '2024-08-14',
              title: 'Engineer',
              primary: true,
              rate: '88000.00',
              paymentUnit: 'Year',
              currentCompensationUuid: '97392ffe-23f1-4197-b5dd-7bd25f236ab3',
              twoPercentShareholder: false,
              stateWcCovered: null,
              stateWcClassCode: null,
              compensations: [
                {
                  uuid: '97392ffe-23f1-4197-b5dd-7bd25f236ab3',
                  version: '47eb13f9dc3266f7f03da6a394d0f4f3',
                  jobUuid: '3716981a-fd79-44bb-b3af-04abf2b4a88c',
                  employeeUuid: '89540375-9ac7-4dc7-9c05-0e8cf14c1633',
                  rate: '88000.00',
                  paymentUnit: 'Year',
                  flsaStatus: 'Nonexempt',
                  effectiveDate: '2025-08-14',
                  adjustForMinimumWage: false,
                  minimumWages: [],
                },
              ],
            },
          ],
          eligiblePaidTimeOff: [],
          terminations: [],
          garnishments: [],
          dateOfBirth: '1979-08-14',
          hasSsn: true,
          ssn: '',
          phone: null,
          preferredFirstName: null,
          paymentMethod: 'Direct Deposit',
          currentEmploymentStatus: 'full_time',
          historical: false,
          employeeCode: '6f4f4c',
          departmentUuid: 'ee2bcaaf-faf3-4813-97d7-873b72692b61',
        },
        {
          uuid: '8e9c8d3d-ce5c-4822-bd27-f197719c1009',
          firstName: 'Alexander',
          middleInitial: null,
          lastName: 'Hamilton',
          email: 'aham661013@initech.biz',
          companyUuid: '624e94a3-da0a-48e1-9f9b-667f8d502ce1',
          managerUuid: '0a5a4dc1-e1c1-4825-9cf2-8717397c5977',
          version: '8d39dde0321eec7056a246131465df79',
          department: 'Engineering',
          terminated: false,
          twoPercentShareholder: false,
          workEmail: null,
          onboarded: true,
          onboardingStatus: 'onboarding_completed',
          onboardingDocumentsConfig: {
            uuid: null,
            i9Document: false,
          },
          jobs: [
            {
              uuid: '589bfc17-cbfe-4ad2-84b4-425f5ffe548f',
              version: '2560c0ca61c86733d45fd0d36df0a7cd',
              employeeUuid: '8e9c8d3d-ce5c-4822-bd27-f197719c1009',
              hireDate: '2024-08-14',
              title: 'Marketing Director',
              primary: true,
              rate: '78000.00',
              paymentUnit: 'Year',
              currentCompensationUuid: 'f4009e42-f10b-458c-8796-cd3a7faf162b',
              twoPercentShareholder: false,
              stateWcCovered: null,
              stateWcClassCode: null,
              compensations: [
                {
                  uuid: 'f4009e42-f10b-458c-8796-cd3a7faf162b',
                  version: 'a4246aa20fcd202dcf9e6988f0c8df63',
                  jobUuid: '589bfc17-cbfe-4ad2-84b4-425f5ffe548f',
                  employeeUuid: '8e9c8d3d-ce5c-4822-bd27-f197719c1009',
                  rate: '78000.00',
                  paymentUnit: 'Year',
                  flsaStatus: 'Exempt',
                  effectiveDate: '2025-08-14',
                  adjustForMinimumWage: false,
                  minimumWages: [],
                },
              ],
            },
          ],
          eligiblePaidTimeOff: [],
          terminations: [],
          garnishments: [],
          dateOfBirth: '1993-08-14',
          hasSsn: true,
          ssn: '',
          phone: null,
          preferredFirstName: null,
          paymentMethod: 'Direct Deposit',
          currentEmploymentStatus: 'full_time',
          historical: false,
          employeeCode: '403baa',
          departmentUuid: 'ee2bcaaf-faf3-4813-97d7-873b72692b61',
        },
        {
          uuid: '2849b9e2-83c2-46b1-9c10-a127da02d117',
          firstName: 'Carlton',
          middleInitial: null,
          lastName: 'Emmerich',
          email: 'ola.lynch+4965cb2222@gusto.com',
          companyUuid: '624e94a3-da0a-48e1-9f9b-667f8d502ce1',
          managerUuid: '0a5a4dc1-e1c1-4825-9cf2-8717397c5977',
          version: '9a61c67f6fc1ae4a53914866169f5be2',
          department: 'Sales',
          terminated: false,
          twoPercentShareholder: false,
          workEmail: null,
          onboarded: true,
          onboardingStatus: 'onboarding_completed',
          onboardingDocumentsConfig: {
            uuid: null,
            i9Document: false,
          },
          jobs: [
            {
              uuid: '4bbc8b1e-4c98-4be5-9a99-32c4ad6b0e7c',
              version: 'f874dfe99508503177afdc866cb29097',
              employeeUuid: '2849b9e2-83c2-46b1-9c10-a127da02d117',
              hireDate: '2024-08-14',
              title: 'Office Administrator',
              primary: true,
              rate: '37.00',
              paymentUnit: 'Hour',
              currentCompensationUuid: 'fee8bdec-4b7c-40d9-a358-cba4ecdac84e',
              twoPercentShareholder: false,
              stateWcCovered: null,
              stateWcClassCode: null,
              compensations: [
                {
                  uuid: 'fee8bdec-4b7c-40d9-a358-cba4ecdac84e',
                  version: 'bb1dbb197ec7bdba17aa0a8f44acdda6',
                  jobUuid: '4bbc8b1e-4c98-4be5-9a99-32c4ad6b0e7c',
                  employeeUuid: '2849b9e2-83c2-46b1-9c10-a127da02d117',
                  rate: '37.00',
                  paymentUnit: 'Hour',
                  flsaStatus: 'Nonexempt',
                  effectiveDate: '2025-08-14',
                  adjustForMinimumWage: false,
                  minimumWages: [],
                },
              ],
            },
          ],
          eligiblePaidTimeOff: [],
          terminations: [],
          garnishments: [],
          dateOfBirth: '1996-02-09',
          hasSsn: true,
          ssn: '',
          phone: null,
          preferredFirstName: null,
          paymentMethod: 'Direct Deposit',
          currentEmploymentStatus: 'full_time',
          historical: false,
          employeeCode: '9cd20a',
          departmentUuid: '2dd0e2c3-2f0f-4c30-9dd8-f2a42c56ae28',
        },
        {
          uuid: 'cd7a9c78-9c7e-460f-ae57-5ba3a4109ff0',
          firstName: 'Angela',
          middleInitial: null,
          lastName: 'Martin',
          email: 'angela.martin-3fb878cfbfa8c6fd612d@gusto.com',
          companyUuid: '624e94a3-da0a-48e1-9f9b-667f8d502ce1',
          managerUuid: null,
          version: 'b84d6da6e31f4183cec11d503c529ef8',
          department: null,
          terminated: false,
          twoPercentShareholder: null,
          workEmail: null,
          onboarded: false,
          onboardingStatus: 'admin_onboarding_incomplete',
          onboardingDocumentsConfig: {
            uuid: null,
            i9Document: false,
          },
          jobs: [],
          eligiblePaidTimeOff: [],
          terminations: [],
          garnishments: [],
          dateOfBirth: null,
          hasSsn: false,
          ssn: '',
          phone: null,
          preferredFirstName: null,
          paymentMethod: 'Check',
          currentEmploymentStatus: null,
          historical: false,
          employeeCode: '289c63',
          departmentUuid: null,
        },
      ]}
    />
  )
}
