#!/bin/bash

# Docker
# -----------------------------------
export AWS_ECR_REPO="${GUSTO_ECR_HOST}/embedded-react-sdk"
export BUILDKITE_BRANCH_SAFE=$(echo $BUILDKITE_BRANCH | sed 's/\W/-/g')
export DOCKER_IMAGE="${AWS_ECR_REPO}:${BUILDKITE_BRANCH_SAFE}-ci"

# Notification
# -----------------------------------
export SLACK_CHANNEL="#emb-proj-frontend-sdk"

# Define variable to describe the build type (PR/MAIN/RELEASE)

# Assume any build on a branch other than main is a PR branch.
BUILD_TYPE=$([ "$BUILDKITE_BRANCH" == "main" ] && echo "MAIN" || echo "PR")

export BUILD_TYPE
